### ISSUE TITLE
filter.py read_csv with line terminator '\n' as sep causes an error

### ISSUE THREAD

**Issue by OrianeN** [ymoslem/OpenNMT-Tutorial#3]
I got the following error when running the notebook 1-NMT-Data-Processing:

![image](https://user-images.githubusercontent.com/59572247/188917306-7e09cb17-23cf-4204-94d1-6a6d20258590.png)

**Comment by ymoslem** [comment]
Hi Oriane!

Thanks for your report!

Could you please give more details about your environment. For example, Pandas version.
```
pip3 freeze | grep pandas
```

I tried the filter.py script with the same FR-EN UN dataset, with Pandas 1.4.4. on Mac OS. I tried it also on Google Colab. I could not replicate the issue in either case. So, I will highly appreciate if you can shed some light on what might be different on your environment. Thanks in advance!

I see you offered a solution [here](https://github.com/ymoslem/MT-Preparation/pull/3). Alternatively, you can try [this solution](https://stackoverflow.com/questions/72795515/read-text-files-with-multiple-lists-with-spacings-and-commas-exist-between-eleme), which replaces `sep="\n"` with `sep="\0"` Does this work for you?

Thanks!
Yasmin

**Comment by ymoslem** [comment]
I am closing this issue. Feel free to reopen it, if needed.
