### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '-2.34575'

### ISSUE THREAD

**Issue by ArtanisTheOne** [ymoslem/OpenNMT-Tutorial#4]
I've followed all instructions with a corpus size of around 300,000 (vocab 25,000) and keep on running into this issues (have tried multiple times, same problem). I've completed all pre-processing, model training etc successfully but the library just errors upon a specific entry in the source.vocab (below)
<img width="293" alt="image" src="https://user-images.githubusercontent.com/52015929/193147992-b3cdcf8b-41ef-4519-8f87-23f2092775df.png">

Do you have any idea how I can resolve my issue?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/52015929/193147881-6910ae95-5cc5-49d8-b651-f7f97d7ed5e6.png">

**Comment by ymoslem** [comment]
Hello!

It seems that you are using the vocab file created by SentencePiece. You should rather use the vocab file created by OpenNMT `onmt_build_vocab`

Alternatively, you can use the script [spm_to_vocab.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/spm_to_vocab.py) to convert a SentencePiece vocab file to OpenNMT-py compilable format. If you rather use OpenNMT-tf, there is a [command](https://opennmt.net/OpenNMT-tf/vocabulary.html#convert-a-sentencepiece-vocabulary-to-opennmt-tf) for this vocab conversion process.

I hope this helps.

Kind regards,
Yasmin
