### ISSUE TITLE
Error in config file

### ISSUE THREAD

**Issue by MaRauder111** [ymoslem/OpenNMT-Tutorial#9]
When I run the tutorial in my colab. It is showing 

`Model dimension must be divisible by the number of heads`

I didn't change any parameter from the config file also.

Can you please help me with it?

**Comment by MaRauder111** [comment]
The issue was `rnn_size` was change to  `hidden_size` as describe in  [opennmt v2 to v3](https://opennmt.net/OpenNMT-py/FAQ.html)

**Comment by ymoslem** [comment]
@MaRauder111 Could you please refer me to the file that currently includes this to fix it, or were you using an old version of the repository? Thanks!

**Comment by MaRauder111** [comment]
In the tutorial [NMT Traning](https://github.com/ymoslem/OpenNMT-Tutorial/blob/main/2-NMT-Training.ipynb) creating config.yaml. Inside the file the command `hidden_size` is now change to `rnn_size` in the newer models as said in the [How do I use my v2 models in v3 ?](https://opennmt.net/OpenNMT-py/FAQ.html) `rnn_size` is now `hidden_size`.
